---
- name: Deploy Docker Container
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker Image
      docker_image:
        name: omar2682/weather-app
        tag: latest
        source: pull

    - name: Run Docker Container
      docker_container:
        name: weather-app
        image: omar2682/weather-app:latest
        state: started
        restart_policy: always
        published_ports:
          - "5000:5000"


