---
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker Image
      command: docker pull omar2682/weather-app:latest

    - name: Run Docker Container
      command: docker run -d --name weather-app -p 5000:5000 omar2682/weather-app:latest

